### PR TITLE
Changed the default STATE size format to MiB

### PR DESCRIPTION
**Pull request by ghost**
Hey if you guys have any questions or concerns about the request just let me know. I will be more than happy to change any aspect of my slight modification. Or even if it get's rejected, I would still really appreciate any feedback you might have to provide.

### CODE REVIEW

**Comment by ethanmad** [comment]
I'd prefer to keep option to enter in GiB, since GiB is usually more easily readable/comprehensible.  Could you come up with a solution allows input in either MiB or GiB?

**Comment by ghost** [comment]
Sure thing, I'll try my best!

**Comment by ethanmad** [comment]
The changes look good to me, but I don't have a spare device to test on to verify. Can you confirm that you tested it? Or @ehegnes, if you have a spare device to test on?

Thanks.

**Comment by ghost** [comment]
Give me a sec to back up my storage, then I'll try give it some thorough testing from start to finish, I was only testing out to see if the console would echo the correct output when trying varying inputs for STATE_SZ_PRECISION. Next time I'll be sure to execute the the entirety of the script. I'll get back to you real soon when I'm finished.

**Pull request merged**
